# Generated by Django 3.0.9 on 2020-08-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
